config/routes.rb
Rails.application.routes.draw do
  get '/signup',  to: 'users#new'
  post '/signup', to: 'users#create'

  root 'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/help',    to: 'static_pages#help'
  get '/contact', to: 'static_pages#contact'
  
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
    
    def convert_to_fortnightly
        freq = self.frequency
        amt = self.amount
        
        if freq == "Weekly"
            return amt * 2
        elsif freq == "Fortnightly"
            return amt
        elsif freq == "Monthly"
            return (amt * 12)/26
        elsif freq == "Yearly"
            return amt / 26
        else
            return 0
        end
    end
    
    def convert_to_weekly
        self.convert_to_fortnightly / 2
    end
    
    def convert_to_monthly
        self.convert_to_fortnightly * 26 / 12 
    end
    
    def convert_to_yearly
        self.convert_to_fortnightly * 26
    end
    
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
            columns_used = %w(title amount frequency)
            csv << columns_used
            all.each do |item|
                csv << item.attributes.values_at(*columns_used)
            end
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    
    before_save { email.downcase! }
    
    has_secure_password
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)+[a-z]\z/i
    
    validates :name,        presence:       true,
                            length:         { maximum: 50 }
                        
    validates :email,       presence:       true, 
                            length:         { maximum: 255 },
                            format:         { with: VALID_EMAIL_REGEX },
                            uniqueness:     { case_sensitive: false }
    
    validates :password,    presence:       true,
                            length:         { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]
  
  include ExpensesHelper
  
  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all.sort { |a, b| b.convert_to_fortnightly <=> a.convert_to_fortnightly }
    @new_expense = Expense.new
    @sum_expenses = sum_fortnightly_amounts(@expenses)
    @frequencies = freq_list
    
    respond_to do |format|
      format.html
      format.csv { send_data @expenses.to_csv, filename: "ExpenseList#{Time.now.in_time_zone("Sydney").strftime("%H%M%S_%d%m%Y")}.csv" }
    end
  end
    

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @frequencies = freq_list
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @frequencies = freq_list
  end

  # GET /expenses/1/edit
  def edit
    @frequencies = freq_list
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to root_url, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to root_url, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount, :frequency)
    end
    
    def sum_fortnightly_amounts(expenses)
        sum_val = 0.0
        expenses.each { |exp| sum_val += exp.convert_to_fortnightly }
        return sum_val
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  private
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    # Returns the full page title on a per page basis
    def full_title(page_title = '')
        base_title = "Paydollies Budgeter"
        if page_title.empty?
            base_title
        else
            page_title + ' | ' + base_title
        end
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    
    def gravatar_for(user, size: 80 )
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        # size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: 'gravatar')
    end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
    </small>
    <nav>
        <ul>
            <li><%= link_to 'About', about_path %></li>
            <li><%= link_to 'Contact', contact_path %></li>
            <li><%= link_to 'News', 'http://news.railstutorial.org/' %></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "paydollies", root_path, id: 'logo' %>
      <button type="button" class="navbar-toggle" id='menu-expand-button' data-toggle='collapse' data-target='#nav-bar-links'>
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <nav class="collapse navbar-collapse" id='nav-bar-links'>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to root_path  do%>
            <span class="navbar-link-text">Home</span> <i class="glyphicon glyphicon-home pull-right"></i>
          <% end %>
        </li>
        <li>
          <%= link_to help_path do %>
            <span class="navbar-link-text">Help</span> <i class="glyphicon glyphicon-question-sign pull-right"></i>
          <% end %>
        </li>
        <%= render 'layouts/navbar_link', text: 'About', linkpath: about_path, glyphtype: 'comment' %>
        <%= render 'layouts/navbar_link', text: 'Contact', linkpath: contact_path, glyphtype: 'envelope' %>
        <li><%= link_to 'Log In', '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_navbar_link.html.erb
<li>
  <%= link_to linkpath do %>
    <span class="navbar-link-text"><%= text %></span> <i class="glyphicon glyphicon-<%= glyphtype %> pull-right"></i>
  <% end %>
</li>

app/views/layouts/_rails_default.html.erb
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<ul class="sidebar-nav" id='side-bar-links'>
  <li>
    <%= link_to root_path do %>
      Home<i class="glyphicon glyphicon-home"></i>
    <% end %>
  </li>
  <li>
    <%= link_to help_path do %>
      Help<i class="glyphicon glyphicon-question-sign"></i>
    <% end %>
  </li>
  <li>
    <%= link_to about_path do %>
      About<i class="glyphicon glyphicon-comment"></i>
    <% end %>
  </li>
  <li>
    <%= link_to contact_path do %>
      Contact<i class="glyphicon glyphicon-envelope"></i>
    <% end %>
  </li>
  <li>
    <%= link_to signup_path do %>
      Sign Up <i class="glyphicon glyphicon-user"></i>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      
      <div class="container">
        <%= render 'layouts/sidebar' %>
          
        <div class="main-content">  <!--col-md-9-->
            <% flash.each do |type, msg| %>
              <%= content_tag(:div, msg, class: "alert alert-#{type}") %>
            <% end %>
            <%= yield %>
        </div>
      <!--</div>-->
  </body>
</html>

app/views/modals/_new_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="newExpenseModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Expense</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@new_expense) do |f| %>
          <% if @new_expense.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@new_expense.errors.count, "error") %> prohibited this expense from being saved:</h2>
        
              <ul>
              <% @new_expense.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
        
          <div class="field">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control', tabindex: 1 %>
          </div>
          
          <div class="field">
            <%= f.label :amount %>
            <div class="input-group">
              <span class="input-group-addon">$</span>
              <%= f.text_field :amount, class: 'form-control text-right', tabindex: 2 %>
            </div>
          </div>
        
          <div class="field">
            <%= f.label :frequency %>
            <%= f.select :frequency, @frequencies, {}, { class: 'form-control', tabindex: 3 } %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal" tabindex=5>Close</button>
        <!--<div class="actions">-->
            <%= f.submit 'Save', class: 'btn btn-primary', tabindex: 4 %>
          <!--</div>-->
      </div>
      <% end %>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
    <!--<div id="error_explanation">-->
    <!--    <div class="alert alert-danger">-->
    <!--        The form contains <%= pluralize(@user.errors.count, "error") %>.-->
    <!--    </div>-->
    <!--    <ul>-->
    <!--        <% @user.errors.full_messages.each do |msg| %>-->
    <!--            <li><%= msg %></li>-->
    <!--        <% end %>-->
    <!--    </ul>-->
    <!--</div>-->
    
    <div class="panel panel-danger" id="error_explanation">
      <div class="panel-heading">
        <h3 class="panel-title">The form contains <%= pluralize(@user.errors.count, "error") %>.</h3>
      </div>
      <div class="panel-body">
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
      </div>
    </div>

<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>

<p>
    The <a href="http://www.railstutorial.org/"><em>Ruby on Rails Tutorial</em></a> is a <a href="http://www.railstutorial.org/book">book</a> and <a href="http://screencasts.railstutorial.org/">screencast series</a> to teach web development with <a href="http://rubyonrails.org/">Ruby on Rails</a>.
    This is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
    Contact the Ruby on Rails Tutorial about the sample app at the <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the <a href="http://www.railstutorial.org/book">Ruby on Rails Tutorial</a> book.
</p>

app/views/static_pages/home.html.erb
<!--<div class="center jumbotron">-->
<!--    <h1>Welcome to the Sample App</h1>-->
    
<!--    <h2>-->
<!--        This is the home page for the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application.-->
<!--    </h2>-->
    
<!--    <%= link_to "Sign up now!", signup_path, class: 'btn btn-lg btn-primary' %>-->
<!--</div>-->

<!--<%= link_to image_tag('rails.png', alt: 'Rails logo'), 'http://rubyonrails.org/' %>-->

<h1>Dashboard</h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">My Budget</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
        <tr>
            <td>Data 1</td>
            <td>Data 2</td>
            <td>Data 3</td>
        </tr>
        <tr>
            <td>Data 4</td>
            <td>Data 5</td>
            <td>Data 6</td>
        </tr>
        <tr>
            <td>Data 7</td>
            <td>Data 8</td>
            <td>Data 9</td>
        </tr>
        <tr>
            <td>Total 1</td>
            <td>Total 2</td>
            <td>Total 3</td>
        </tr>
    </table>
  </div>
  <div class="panel-footer text-right">
      <%= link_to 'see more...', help_path %>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">My Incomes</h3>
  </div>
  <div class="panel-body">
    <table class="table table-hover">
        <tr>
            <th>Employer</th>
            <th>Pay</th>
            <th>Frequency</th>
        </tr>
        <tr>
            <td>ATO</td>
            <td>$1,500.00</td>
            <td>Fortnight</td>
        </tr>
        <tr>
            <td>Library</td>
            <td>$1,104.19</td>
            <td>Month</td>
        </tr>
        <tr>
            <td>Downer</td>
            <td>$0.00</td>
            <td>Like, ever</td>
        </tr>
    </table>
  </div>
  <div class="panel-footer  text-right">
      <%= link_to 'see more...', about_path %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign Up</h1>

<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <%= form_for @user, url: signup_path do |f| %>
            <%= render 'shared/error_messages' %>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.label :password_confirmation, 'Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.submit 'Create my account', class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user, size: 50 %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
</div>